### ISSUE TITLE
CF push of spring-music app with v7 CLI fails after building app image

### ISSUE THREAD

**Issue by emalm** [cloudfoundry/cf-for-k8s#287]
## Describe the bug

Pushing the [spring-music sample CF app](https://github.com/cloudfoundry-samples/spring-music) against an up-to-date cf-for-k8s installation with the v7 CLI builds the image successfully, but fails to start the app. Running `cf start spring-music` also fails as a command, but the app does then start in the background.

Tracing the `cf push` command shows that Cloud Controller is returning a 500 on a `POST` to the `/v3/apps/:app_guid/actions/restart` endpoint.

Pushing this app with the v6 CLI does succeed, though.

FYI @cloudfoundry/cf-capi 

## To Reproduce

1. Install cf-for-k8s from latest master-branch build
2. Target an org and space in the installation with the latest v7 CF CLI.
3. Clone [spring-music](https://github.com/cloudfoundry-samples/spring-music) and build its JAR file locally with gradle.
4. Push the spring-music app and observe that it fails with a 500 status-code error from a CC API call after building the image.

<details>
<summary>CF push failure</summary>

```
$ CF_TRACE=true cf push spring-music
(snip)
REQUEST: [2020-07-16T08:59:34-07:00]
PATCH /v3/apps/5b2a9a19-dd50-4c95-974b-38e4be1db608/relationships/current_droplet HTTP/1.1
Host: api.c4k.haas-424.pez.vmware.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
Content-Type: application/json
User-Agent: cf/7.0.1+fb3f929c2.2020-06-24 (go1.13.8; amd64 darwin)
{
  "data": {
    "guid": "7a1b8445-741f-48aa-a900-deb1d465d464"
  }
}


RESPONSE: [2020-07-16T08:59:34-07:00]
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
Date: Thu, 16 Jul 2020 15:59:34 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: istio-envoy
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Envoy-Upstream-Service-Time: 102
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Runtime: 0.085240
X-Vcap-Request-Id: 21283f64-dc81-4705-ba93-4756eab4a24e::34e144b5-9453-4db3-ad75-8e9c2c2055df
X-Xss-Protection: 1; mode=block
{
  "data": {
    "guid": "7a1b8445-741f-48aa-a900-deb1d465d464"
  },
  "links": {
    "related": {
      "href": "https://api.c4k.haas-424.pez.vmware.com/v3/apps/5b2a9a19-dd50-4c95-974b-38e4be1db608/droplets/current"
    },
    "self": {
      "href": "https://api.c4k.haas-424.pez.vmware.com/v3/apps/5b2a9a19-dd50-4c95-974b-38e4be1db608/relationships/current_droplet"
    }
  }
}

Waiting for app spring-music to start...

REQUEST: [2020-07-16T08:59:34-07:00]
POST /v3/apps/5b2a9a19-dd50-4c95-974b-38e4be1db608/actions/restart HTTP/1.1
Host: api.c4k.haas-424.pez.vmware.com
Accept: application/json
Authorization: [PRIVATE DATA HIDDEN]
User-Agent: cf/7.0.1+fb3f929c2.2020-06-24 (go1.13.8; amd64 darwin)

RESPONSE: [2020-07-16T08:59:35-07:00]
HTTP/1.1 500 Internal Server Error
Content-Type: application/json; charset=utf-8
Date: Thu, 16 Jul 2020 15:59:35 GMT
Referrer-Policy: strict-origin-when-cross-origin
Server: istio-envoy
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Envoy-Upstream-Service-Time: 482
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Runtime: 0.453171
X-Vcap-Request-Id: 2956c47b-b491-4c50-ac6a-d2ecf5e89715::053bff97-eea9-497c-80e1-2cd25b533bf7
X-Xss-Protection: 1; mode=block
{
  "errors": [
    {
      "code": 10001,
      "detail": "An unknown error occurred.",
      "title": "UnknownError"
    }
  ]
}
```
</details>

<details>
<summary>Stacktrace in CC logs</summary>

```
$ kapp logs -a cf -m cf-api-server% -c cf-api-server -f
(snip)
cf-api-server-7b7bd77f98-xscg5 > cf-api-server | {"timestamp":"2020-07-16T15:59:35.459408695Z","message":"Request failed: 500: {\"errors\"=>[{\"title\"=>\"UnknownError\", \"detail\"=>\"An unknown error occurred.\", \"code\"=>10001, \"test_mode_info\"=>{\"detail\"=>\"HTTPClient::KeepAliveDisconnected: \", \"title\"=>\"CF-KeepAliveDisconnected\", \"backtrace\"=>[\"/usr/local/lib/ruby/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:808:in `block in parse_header'\", \"/usr/local/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'\", \"/usr/local/lib/ruby/2.5.0/timeout.rb:103:in `timeout'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:801:in `parse_header'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:784:in `read_header'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:561:in `get_header'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:1299:in `do_get_header'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:1245:in `do_get_block'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:1138:in `rescue in protect_keep_alive_disconnected'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:1131:in `protect_keep_alive_disconnected'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:856:in `request'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/httpclient-2.8.3/lib/httpclient.rb:775:in `put'\", \"/cloud_controller_ng/lib/cloud_controller/opi/apps_client.rb:17:in `desire_app'\", \"/cloud_controller_ng/lib/cloud_controller/diego/desire_app_handler.rb:10:in `create_or_update_app'\", \"/cloud_controller_ng/lib/cloud_controller/diego/messenger.rb:28:in `send_desire_request'\", \"/cloud_controller_ng/lib/cloud_controller/diego/runner.rb:23:in `block in start'\", \"/cloud_controller_ng/lib/cloud_controller/diego/runner.rb:41:in `with_logging'\", \"/cloud_controller_ng/lib/cloud_controller/diego/runner.rb:23:in `start'\", \"/cloud_controller_ng/lib/cloud_controller/backends/copilot_runner_delegator.rb:17:in `start'\", \"/cloud_controller_ng/app/actions/process_restart.rb:23:in `block in restart'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/database/transactions.rb:229:in `block in transaction'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/database/connecting.rb:270:in `synchronize'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/database/transactions.rb:199:in `transaction'\", \"/cloud_controller_ng/app/actions/process_restart.rb:8:in `restart'\", \"/cloud_controller_ng/app/actions/app_restart.rb:18:in `block (2 levels) in restart'\", \"/cloud_controller_ng/app/actions/app_restart.rb:17:in `each'\", \"/cloud_controller_ng/app/actions/app_restart.rb:17:in `block in restart'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/database/transactions.rb:258:in `_transaction'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/database/transactions.rb:233:in `block in transaction'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/database/connecting.rb:270:in `synchronize'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/sequel-5.22.0/lib/sequel/database/transactions.rb:199:in `transaction'\", \"/cloud_controller_ng/app/actions/app_restart.rb:13:in `restart'\", \"/cloud_controller_ng/app/controllers/v3/apps_controller.rb:206:in `restart'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/abstract_controller/base.rb:194:in `process_action'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/rendering.rb:30:in `process_action'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:132:in `run_callbacks'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/abstract_controller/callbacks.rb:41:in `process_action'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/rescue.rb:22:in `process_action'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:168:in `block in instrument'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:168:in `instrument'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/abstract_controller/base.rb:134:in `process'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionview-5.2.4.3/lib/action_view/rendering.rb:32:in `process'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_controller/metal.rb:191:in `dispatch'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_controller/metal.rb:252:in `dispatch'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:34:in `serve'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/journey/router.rb:52:in `block in serve'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/journey/router.rb:35:in `each'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/journey/router.rb:35:in `serve'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:840:in `call'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:98:in `run_callbacks'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/executor.rb:14:in `call'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'\", \"/cloud_controller_ng/middleware/request_logs.rb:38:in `call'\", \"/cloud_controller_ng/middleware/security_context_setter.rb:19:in `call'\", \"/cloud_controller_ng/middleware/vcap_request_id.rb:15:in `call'\", \"/cloud_controller_ng/middleware/cors.rb:49:in `call_app'\", \"/cloud_controller_ng/middleware/cors.rb:14:in `call'\", \"/cloud_controller_ng/middleware/request_metrics.rb:12:in `call'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:50:in `block in process'\", \"/usr/local/lib/ruby/gems/2.5.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1067:in `block in spawn_threadpool'\"]}}]}","log_level":"error","source":"cc.api","data":{"request_guid":"2956c47b-b491-4c50-ac6a-d2ecf5e89715::053bff97-eea9-497c-80e1-2cd25b533bf7"},"thread_id":47227938764260,"fiber_id":47227937214680,"process_id":1,"file":"/cloud_controller_ng/app/controllers/v3/errors_controller.rb","lineno":11,"method":"internal_error"}
```
</details>

## Expected behavior

`cf push` should exit with status 0 and the app should be running afterwards.

### cf-for-k8s SHA 

https://github.com/cloudfoundry/cf-for-k8s/commit/6a4bf75106f1c3b5625579f4c91df94b5533c0ad

### Deploy instructions

```
ytt -f config -f ~/workspace/environments/haas-424/cf-for-k8s-values | kapp deploy -a cf -y -f-
```

### Cluster information

TKGI v1.8 (k8s 1.17.5) on vSphere with NSX-T container networking.

### CLI versions
_paste output of the following commands_

1. `ytt --version`: `ytt version 0.28.0`
2. `kapp --version`: `kapp version 0.30.0`
3. `kubectl version`:
  ```
  Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-07-04T14:53:16Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
  Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5+vmware.1", GitCommit:"f8b685623a975d20a9b35685c24611c44d464b3b", GitTreeState:"clean", BuildDate:"2020-05-01T21:32:30Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
  ```
4. `cf version`: `cf version 7.0.1+fb3f929c2.2020-06-24`

**Comment by emalm** [comment]
As another data point, I see the same error when pushing the [java](https://github.com/cloudfoundry/cf-acceptance-tests/tree/master/assets/java) app from the CF acceptance tests with the v7 CLI.

**Comment by selzoc** [comment]
Replicated this on my environment with the java app from CATs.  Here is one level deeper of logs from `eirini` (the java app's guid is `e9ae3554-fb1c-40cb-b310-464124ad2a95`):
```
 {"timestamp":"2020-07-22T14:38:13.213363528Z","level":"debug","source":"handler","message":"handler.desire-app.requested","data":{"app_guid":"e9ae3554-fb1c-40cb-b310-464124ad2a95"
 ,"guid":"dc3121ef-0c16-433e-be4e-12ee667cc24c-f2ad251f-541c-45d0-a728-075157e2ea0e","session":"51798","version":"f2ad251f-541c-45d0-a728-075157e2ea0e"}}
 2020/07/22 14:38:13 http: panic serving 127.0.0.1:35244: runtime error: index out of range [0] with length 0
 goroutine 119659 [running]:
 net/http.(*conn).serve.func1(0xc000352c80)
     net/http/server.go:1767 +0x139
 panic(0x181c8e0, 0xc00076d980)
     runtime/panic.go:679 +0x1b2
 code.cloudfoundry.org/eirini/bifrost.(*OPIConverter).ConvertLRP(0xc00048a080, 0xc00074eb70, 0x24, 0xc00074eba0, 0x24, 0xc00003e690, 0x49, 0xc0002c1990, 0x4, 0xc00074ec00, ...)
     code.cloudfoundry.org/eirini@/bifrost/convert.go:50 +0x1120
 code.cloudfoundry.org/eirini/bifrost.(*LRP).Transfer(0xc0005b3d10, 0x1b9eae0, 0xc0008b8180, 0xc00074eb70, 0x24, 0xc00074eba0, 0x24, 0xc00003e690, 0x49, 0xc0002c1990, ...)
     code.cloudfoundry.org/eirini@/bifrost/lrp.go:36 +0xc0
 code.cloudfoundry.org/eirini/handler.(*App).Desire(0xc00000d380, 0x1b98da0, 0xc00047a620, 0xc0000dd200, 0xc000594960, 0x1, 0x3)
     code.cloudfoundry.org/eirini@/handler/app_handler.go:45 +0x55b
 github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0003484e0, 0x1b98da0, 0xc00047a620, 0xc0000dd200)
     github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0xa3d
 net/http.serverHandler.ServeHTTP(0xc0005b4ee0, 0x1b98da0, 0xc00047a620, 0xc0000dd200)
     net/http/server.go:2802 +0xa4
 net/http.(*conn).serve(0xc000352c80, 0x1b9eae0, 0xc00041dac0)
     net/http/server.go:1890 +0x875
 created by net/http.(*Server).Serve
     net/http/server.go:2928 +0x384
 2020/07/22 14:38:13 http: panic serving 127.0.0.1:35246: runtime error: index out of range [0] with length 0
 goroutine 119664 [running]:
 net/http.(*conn).serve.func1(0xc0002921e0)
     net/http/server.go:1767 +0x139
 panic(0x181c8e0, 0xc0005bc560)
     runtime/panic.go:679 +0x1b2
 code.cloudfoundry.org/eirini/bifrost.(*OPIConverter).ConvertLRP(0xc00048a080, 0xc00074f200, 0x24, 0xc00074f230, 0x24, 0xc00003edc0, 0x49, 0xc0007b4378, 0x4, 0xc00074f260, ...)
     code.cloudfoundry.org/eirini@/bifrost/convert.go:50 +0x1120
 code.cloudfoundry.org/eirini/bifrost.(*LRP).Transfer(0xc0005b3d10, 0x1b9eae0, 0xc0008b8480, 0xc00074f200, 0x24, 0xc00074f230, 0x24, 0xc00003edc0, 0x49, 0xc0007b4378, ...)
     code.cloudfoundry.org/eirini@/bifrost/lrp.go:36 +0xc0
 code.cloudfoundry.org/eirini/handler.(*App).Desire(0xc00000d380, 0x1b98da0, 0xc00047ab60, 0xc00095f200, 0xc000595a40, 0x1, 0x3)
     code.cloudfoundry.org/eirini@/handler/app_handler.go:45 +0x55b
 github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0003484e0, 0x1b98da0, 0xc00047ab60, 0xc00095f200)
     github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0xa3d
 net/http.serverHandler.ServeHTTP(0xc0005b4ee0, 0x1b98da0, 0xc00047ab60, 0xc00095f200)
     net/http/server.go:2802 +0xa4
 net/http.(*conn).serve(0xc0002921e0, 0x1b9eae0, 0xc0008b83c0)
     net/http/server.go:1890 +0x875
 created by net/http.(*Server).Serve
     net/http/server.go:2928 +0x384
 {"timestamp":"2020-07-22T14:38:13.243981833Z","level":"debug","source":"handler","message":"handler.desire-app.requested","data":{"app_guid":"e9ae3554-fb1c-40cb-b310-464124ad2a95"
 ,"guid":"dc3121ef-0c16-433e-be4e-12ee667cc24c-f2ad251f-541c-45d0-a728-075157e2ea0e","session":"51799","version":"f2ad251f-541c-45d0-a728-075157e2ea0e"}}
 {"timestamp":"2020-07-22T14:38:28.016241248Z","level":"debug","source":"handler","message":"handler.list-apps.requested","data":{"session":"51800"}}
 {"timestamp":"2020-07-22T14:38:28.047216626Z","level":"debug","source":"handler","message":"handler.stop-app.requested","data":{"guid":"e9ae3554-fb1c-40cb-b310-464124ad2a95","sess
 ion":"51801","version":""}}
```

**Comment by selzoc** [comment]
That `eirini` line that explodes seems to be:

https://github.com/cloudfoundry-incubator/eirini/blob/ab3b5d505040519e82e0d3b63dc2cdc8a5636b4e/bifrost/convert.go#L50
```
...
func (c *OPIConverter) ConvertLRP(request cf.DesireLRPRequest) (opi.LRP, error) {
	var command []string
	var env map[string]string
	var image string
	var privateRegistry *opi.PrivateRegistry
	var runsAsRoot bool

	port := request.Ports[0]
...
```

So maybe somehow there are no ports on the LRP request coming from capi.

**Comment by selzoc** [comment]
Following breadcrumbs:

Where the LRP request gets the ports (`process.open_ports`): https://github.com/cloudfoundry/cloud_controller_ng/blob/7220f9cbda29979818f6d4130b14f43a0096541a/lib/cloud_controller/opi/apps_client.rb#L145

That method on the `process` model: https://github.com/cloudfoundry/cloud_controller_ng/blob/7220f9cbda29979818f6d4130b14f43a0096541a/app/models/runtime/process_model.rb#L565-L583

**Comment by emalm** [comment]
@selzoc interesting, I did notice that there are two non-`web` processes for the app (`executable-jar` and `task`) and that they don't seem to have routes mapped to them. Maybe Eirini is choking on those ones?

**Comment by selzoc** [comment]
I annotated the `open_ports` method as such:
```
    def open_ports
      puts "---- process type: #{type}"
      puts '----- in open ports'
      open_ports = ports || []
      puts "----- ports: #{ports}"

      if docker?
        puts "----- i AM docker"
        has_mapping_without_port = route_mappings.any? { |mapping| !mapping.has_app_port_specified? }
        needs_docker_ports = docker_ports.present? && (has_mapping_without_port || open_ports.empty?)

        if needs_docker_ports
          open_ports += docker_ports
        end

        if !docker_ports.present? && has_mapping_without_port
          open_ports += DEFAULT_PORTS
        end
      end

      puts "----- open_ports 1: #{open_ports}"
      puts "----- web?: #{web?} - open_ports.empty? #{open_ports.empty?}"
      open_ports += DEFAULT_PORTS if web? && open_ports.empty?
      puts "----- open_ports 2: #{open_ports}"
      open_ports.uniq
    end
```

which results in when pushing the java app:
```
 ---- process type: web
 ----- in open ports
 ----- ports:
 ----- open_ports 1: []
 ----- web?: true - open_ports.empty? true
 ----- open_ports 2: [8080]
 ---- process type: web
 ----- in open ports
 ----- ports:
 ----- open_ports 1: []
 ----- web?: true - open_ports.empty? true
 ----- open_ports 2: [8080]
 ---- process type: task
 ----- in open ports
 ----- ports:
 ----- open_ports 1: []
 ----- web?: false - open_ports.empty? true
 ----- open_ports 2: []
 ---- process type: task
 ----- in open ports
 ----- ports:
 ----- open_ports 1: []
 ----- web?: false - open_ports.empty? true
 ----- open_ports 2: []
```

**Comment by selzoc** [comment]
Verified that the process that is failing is the `task` process:
```
 ---- process type: task
 ---- process guid-process version: 4bc10212-cc35-465f-8ae4-d6070a07a74e-f2fda1ef-fd59-42dd-99e6-455de1cc535e
 ----- in open ports
 ----- ports:
 ----- open_ports 1: []
 ----- web?: false - open_ports.empty? true
 ----- open_ports 2: []
```

eirini logs:
```
{
  "timestamp": "2020-07-22T15:50:39.627781587Z",
  "level": "debug",
  "source": "handler",
  "message": "handler.desire-app.requested",
  "data": {
    "app_guid": "c53dc5d4-d4f5-44d9-8a95-53afe767c91a",
    "guid": "4bc10212-cc35-465f-8ae4-d6070a07a74e-f2fda1ef-fd59-42dd-99e6-455de1cc535e",
    "session": "52111",
    "version": "f2fda1ef-fd59-42dd-99e6-455de1cc535e"
  }
}
 2020/07/22 15:50:39 http: panic serving 127.0.0.1:42910: runtime error: index out of range [0] with length 0
```

**Comment by selzoc** [comment]
Not sure why we're desiring a LRP for the `task` process since it has 0 instances:
```
→ cf curl /v3/apps/$(cf app java --guid)/processes | jq '.resources[] | .type + ": " +  (.instances|tostring)'
"web: 1"
"task: 0"
"tomcat: 0"
```

**Comment by selzoc** [comment]
It actually looks like the instance count is a red herring.  Diego/Eirini are perfectly happy with a lrp with 0 instances.  The difficulty comes in providing an empty array of ports.

The diego path _always_ provides a port: https://github.com/cloudfoundry/cloud_controller_ng/blob/7220f9cbda29979818f6d4130b14f43a0096541a/lib/cloud_controller/diego/buildpack/desired_lrp_builder.rb#L99-L103

**Comment by braunsonm** [comment]
Hey guys, just reporting here that I cannot replicate this issue anymore. I am able to deploy spring music without issues on my cluster I threw up today.

**Comment by emalm** [comment]
Yes, I've also verified that this now works. I'll close out this issue.
