### ISSUE TITLE
Pushing Docker apps broken

### ISSUE THREAD

**Issue by XanderStrike** [cloudfoundry/cf-for-k8s#465]
## Describe the bug
When attempting to `cf push` a docker app, we get an error.

## To Reproduce*
1. Deploy cf-for-k8s develop
2. Attempt to `cf push myapp -o cfrouting/httpbin`

## Observed behavior

CF CLI returns the following error:

```
$ cf push fdsaasdf -o cfrouting/proxy
Pushing app fdsaasdf to org o / space s as admin...

Staging app and tracing logs...
Unexpected Response
Response Code: 500
Request ID:    e7db2a5f-530d-4f40-b142-093ef2da258e::86852fdd-6f20-4595-8f94-dbad271d92a3
Code: 0, Title: , Detail: {
  "errors": [
    {
      "detail": "Runner error: staging task with guid 42603117-8ec8-4b4b-92f0-206279fc21db failed to start",
      "title": "CF-RunnerError",
      "code": 170016
    }
  ]
}
FAILED
```

CF API server shows this error:

<details><summary>Click to expand!</summary>

```
{
  "timestamp": "2020-09-22T17:11:30.374308214Z",
  "message": "Request failed: 500: {
        \"errors\"=>[
            {
                \"detail\"=>\"Runner error: staging task with guid 6fe044f5-fe2d-4524-86fa-ca9a861ecd10 failed to start\", 

                \"title\"=>\"CF-RunnerError\", 
                \"code\"=>170016, 
                \"test_mode_info\"=>{
                    \"detail\"=>\"Runner error: staging task with guid 6fe044f5-fe2d-4524-86fa-ca9a861ecd10 failed to start\", 
                    \"title\"=>\"CF-RunnerError\", 
                    \"backtrace\"=>[
                        \"/cloud_controller_ng/lib/cloud_controller/opi/stager_client.rb:84:in `start_staging'\", 
                        \"/cloud_controller_ng/lib/cloud_controller/opi/stager_client.rb:18:in `stage'\", 
                        \"/cloud_controller_ng/lib/cloud_controller/diego/messenger.rb:16:in `send_stage_request'\", 
                        \"/cloud_controller_ng/lib/cloud_controller/diego/stager.rb:32:in `send_stage_package_request'\", 
                        \"/cloud_controller_ng/lib/cloud_controller/diego/stager.rb:9:in `stage'\", 
                        \"/cloud_controller_ng/app/actions/build_create.rb:77:in `create_and_stage'\", 
                        \"/cloud_controller_ng/app/controllers/v3/builds_controller.rb:44:in `create'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/abstract_controller/base.rb:194:in `process_action'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/rendering.rb:30:in `process_action'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:132:in `run_callbacks'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/abstract_controller/callbacks.rb:41:in `process_action'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/rescue.rb:22:in `process_action'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:168:in `block in instrument'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/notifications.rb:168:in `instrument'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/abstract_controller/base.rb:134:in `process'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/actionview-5.2.4.3/lib/action_view/rendering.rb:32:in `process'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_controller/metal.rb:191:in `dispatch'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_controller/metal.rb:252:in `dispatch'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:34:in `serve'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/journey/router.rb:52:in `block in serve'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/journey/router.rb:35:in `each'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/journey/router.rb:35:in `serve'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/routing/route_set.rb:840:in `call'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/callbacks.rb:98:in `run_callbacks'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.2.4.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/executor.rb:14:in `call'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `each'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'\", 
                        \"/cloud_controller_ng/middleware/request_logs.rb:38:in `call'\", 
                        \"/cloud_controller_ng/middleware/security_context_setter.rb:19:in `call'\", 
                        \"/cloud_controller_ng/middleware/vcap_request_id.rb:15:in `call'\", 
                        \"/cloud_controller_ng/middleware/cors.rb:49:in `call_app'\", 
                        \"/cloud_controller_ng/middleware/cors.rb:14:in `call'\", 
                        \"/cloud_controller_ng/middleware/request_metrics.rb:12:in `call'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/thin-1.7.2/lib/thin/connection.rb:50:in `block in process'\", 
                        \"/usr/local/lib/ruby/gems/2.5.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1067:in `block in spawn_threadpool'\"
                        ]
                    }}]}",
  "log_level": "info",
  "source": "cc.api",
  "data": {
    "request_guid": "2ecf42ae-e976-4626-b762-a410143e02d8::f20fb82d-fc63-4def-9369-078cce261a2e"
  },
  "thread_id": 47212068401020,
  "fiber_id": 47212067467880,
  "process_id": 1,
  "file": "/cloud_controller_ng/app/controllers/v3/application_controller.rb",
  "lineno": 190,
  "method": "handle_exception"
}
```
</details>

## Expected behavior
App runs.

### cf-for-k8s SHA 
4c864469f2dd7f86d7a259e985b8a707c6ab1f2b

### Deploy instructions
https://github.com/cloudfoundry/cf-k8s-networking/blob/develop/hack/cf4k8s/methods.sh#L50-L60

### Cluster information
GKE 

### CLI versions

```
$ ytt --version
ytt version 0.30.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-gke.1504", GitCommit:"fb367de18820fe57bac5d97ad60b7a2cef8765e9", GitTreeState:"clean", BuildDate:"2020-09-09T01:00:23Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
$ kapp --version
kapp version 0.34.0
$ cf version
cf version 7.1.0+4c3168f9a.2020-09-09
```

**Comment by tcdowney** [comment]
Logs from the `eirini` pod:

```
eirini-5f5d9f969c-bsff9 > opi | 2020/09/22 17:27:16 [DEBUG] POST http://TODO:TODO@capi.cf-system.svc.cluster.local:80/internal/v3/staging/b3531c47-6988-4e18-b277-51a14d9cb282/build_completed?start=false
eirini-5f5d9f969c-bsff9 > opi | {"timestamp":"2020-09-22T17:27:16.182412696Z","level":"error","source":"handler","message":"handler.staging-handler.staging-request.staging-failed","data":{"error":"staging task with guid b3531c47-6988-4e18-b277-51a14d9cb282 failed to start: callback-response-unsuccessful: request failed: code 403","session":"1.6","staging-guid":"b3531c47-6988-4e18-b277-51a14d9cb282"}}
```

Looks like we broke the staging completion callback for docker apps on Eirini when working on https://www.pivotaltracker.com/story/show/174455375

**Comment by tcdowney** [comment]
Fortunately there should be no Eirini change required... the staging completion callback is controlled fully by CCNG:
https://github.com/cloudfoundry/cloud_controller_ng/blob/aa19fd5c71af54be7b7fa228926161c563e8a26b/lib/cloud_controller/opi/stager_client.rb#L119-L132

**Comment by jspawar** [comment]
Just submitted hopefully the last PR to resolve this issue: https://github.com/cloudfoundry/cf-for-k8s/pull/469

**Comment by jspawar** [comment]
@XanderStrike Looks like this change has made it into the `develop` branch of `cf-for-k8s` already: https://github.com/cloudfoundry/cf-for-k8s/commit/2554e6dc5a5b8ac96ae1ceed326abda7d116c683

Let us know if you all are still experiencing issues with Docker lifecycle apps please

**Comment by Birdrock** [comment]
Confirmed this works on our side. @XanderStrike as @jspawar said, please let us know if this continues to occur for you.

**Comment by XanderStrike** [comment]
Our tests are green! Thank y'all so much.
