### ISSUE TITLE
cf-api-clock crashed

### ISSUE THREAD

**Issue by macevil** [cloudfoundry/cf-for-k8s#563]
## Describe the bug
The cf-api-clock Pod crashed after a certain time and keeps crashing.

## To Reproduce*
1. kapp Installation of `cf-4-k8s` like described here: https://github.com/cloudfoundry/cf-for-k8s/blob/develop/docs/getting-started-tutorial.md
2. See pod error
```
kubectl logs cf-api-clock-77fcc5558c-xdn62 cf-api-clock -n cf-system
```
```
Caused by:
Yajl::ParseError: lexical error: invalid char in json text.
                                       upstream connect error or disco
                     (right here) ------^
/layers/paketo-buildpacks_bundle-install/gems/gems/yajl-ruby-1.4.1/lib/yajl.rb:44:in `parse'
/layers/paketo-buildpacks_bundle-install/gems/gems/yajl-ruby-1.4.1/lib/yajl.rb:44:in `parse'
/layers/paketo-buildpacks_bundle-install/gems/gems/yajl-ruby-1.4.1/lib/yajl/json_gem/parsing.rb:13:in `parse'
/workspace/lib/cloud_controller/opi/apps_client.rb:24:in `fetch_scheduling_infos'
/workspace/lib/cloud_controller/diego/processes_sync.rb:22:in `sync'
/workspace/app/jobs/diego/sync.rb:17:in `block in perform'
/layers/paketo-buildpacks_bundle-install/gems/gems/statsd-ruby-1.4.0/lib/statsd.rb:412:in `time'
/workspace/app/jobs/diego/sync.rb:16:in `perform'
/workspace/app/jobs/wrapping_job.rb:13:in `perform'
/workspace/app/jobs/timeout_job.rb:13:in `block in perform'
/workspace/app/jobs/timeout_job.rb:12:in `perform'
/layers/paketo-buildpacks_bundle-install/gems/gems/delayed_job-4.1.8/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/layers/paketo-buildpacks_bundle-install/gems/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:61:in `block in initialize'
/layers/paketo-buildpacks_bundle-install/gems/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:66:in `execute'
/layers/paketo-buildpacks_bundle-install/gems/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/layers/paketo-buildpacks_bundle-install/gems/gems/delayed_job-4.1.8/lib/delayed/backend/base.rb:78:in `invoke_job'
/layers/paketo-buildpacks_bundle-install/gems/gems/delayed_job-4.1.8/lib/delayed/backend/base.rb:19:in `block (2 levels) in enqueue_job'
/layers/paketo-buildpacks_bundle-install/gems/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:61:in `block in initialize'
/layers/paketo-buildpacks_bundle-install/gems/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:66:in `execute'
/layers/paketo-buildpacks_bundle-install/gems/gems/delayed_job-4.1.8/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/layers/paketo-buildpacks_bundle-install/gems/gems/delayed_job-4.1.8/lib/delayed/backend/base.rb:17:in `block in enqueue_job'
/layers/paketo-buildpacks_bundle-install/gems/gems/delayed_job-4.1.8/lib/delayed/backend/base.rb:16:in `tap'
/layers/paketo-buildpacks_bundle-install/gems/gems/delayed_job-4.1.8/lib/delayed/backend/base.rb:16:in `enqueue_job'
/layers/paketo-buildpacks_bundle-install/gems/gems/delayed_job-4.1.8/lib/delayed/backend/base.rb:12:in `enqueue'
/workspace/app/jobs/enqueuer.rb:34:in `block in run_inline'
/workspace/app/jobs/enqueuer.rb:58:in `run_immediately'
/workspace/app/jobs/enqueuer.rb:33:in `run_inline'
/workspace/lib/cloud_controller/clock/clock.rb:51:in `block in schedule_frequent_inline_job'
/workspace/lib/cloud_controller/clock/clock.rb:58:in `block in schedule_job'
/workspace/lib/cloud_controller/clock/distributed_scheduler.rb:12:in `block (2 levels) in schedule_periodic_job'
/workspace/lib/cloud_controller/clock/distributed_executor.rb:30:in `execute_job'
/workspace/lib/cloud_controller/clock/distributed_scheduler.rb:12:in `block in schedule_periodic_job'
/layers/paketo-buildpacks_bundle-install/gems/gems/clockwork-2.0.4/lib/clockwork/event.rb:58:in `execute'
/layers/paketo-buildpacks_bundle-install/gems/gems/clockwork-2.0.4/lib/clockwork/event.rb:41:in `block in run'
Tasks: TOP => clock:start
(See full trace by running task with --trace)
```

## Expected behavior
The cf-api-clock Pod keeps running.

### Deploy instructions
```
$ ./hack/generate-values.sh -d vcap.me > ${TMP_DIR}/cf-values.yml
$ cat << EOF >> ${TMP_DIR}/cf-values.yml
app_registry:
  hostname: https://index.docker.io/v1/
  repository_prefix: "<my_username>"
  username: "<my_username>"
  password: "<my_password>"

$ kapp deploy -a cf -f <(ytt -f config -f ${TMP_DIR}/cf-values.yml)
```

### Cluster information
GKE Cluster 1.18.0-gke.1501

### CLI versions
1. `ytt --version`: 0.30.0
2. `kapp --version`: 0.34.0
3. `kubectl version`: 
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-gke.1501", GitCommit:"9eccd76926a6de5029d61bd586d7d68fe13b545a", GitTreeState:"clean", BuildDate:"2020-10-07T18:19:12Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
4. `cf version`: 7.1.0+4c3168f9a.2020-09-09

**Comment by acosta11** [comment]
Hi @macevil ,

Thank you for raising this issue. Based on a Slack conversation in the cloudfoundry #cf-for-k8s channel: https://cloudfoundry.slack.com/archives/CH9LF6V1P/p1604432612047900 we think this behavior stems from an incompatibility between a since-reverted version of cf-api-clock and eirini.

The revert was merged in https://github.com/cloudfoundry/cloud_controller_ng/commit/111c2347569c61c00f4d52321a4e92a6bd8f28cb, an image of which was subsequently built based on https://github.com/cloudfoundry/cloud_controller_ng/commit/dccd66101eb7e07e75a2cb4a5d29ee8d0d7f8433. That image was integrated into capi-k8s-release in https://github.com/cloudfoundry/capi-k8s-release/commit/1294bdd84daddcb3f7058c38b20097177cdeb70f and finally  integrated into cf-for-k8s in dff109225205ab1ad3ba78525fbe284cfb853ec3.

If you deploy from a commit of main at or after dff109225205ab1ad3ba78525fbe284cfb853ec3, does the crashing persist?

Thanks,
Andrew and @davewalter

**Comment by macevil** [comment]
Hello @acosta11 and @davewalter ,
thanks a lot! The clock is running again and does not crash!

Johannes
